# SPDX-License-Identifier: Apache-2.0
"""Human-readable report.md (English) with the gaps summary.

States what the declared chain contains and where it is incomplete; ends with
the boundary sentence. The whole output is factual (invariant 3).
"""
from __future__ import annotations

from filo.catalog_en import BOUNDARY_SENTENCE, assert_factual
from filo.ir import AccessStatus, Chain, LicenseConfidence


def _license_cell(a) -> str:
    if not a.licenses:
        return "—"
    la = a.licenses[0]
    if la.confidence is LicenseConfidence.ABSENT:
        return "none declared"
    label = la.spdx_id or la.raw_value or "declared"
    return f"{label} ({la.confidence.value})"


def _count(chain: Chain, pred) -> int:
    return sum(1 for a in chain.artifacts.values() if pred(a))


def _has(a, c) -> bool:
    return any(lic.confidence is c for lic in a.licenses)


def to_report_md(chain: Chain) -> str:
    lines: list[str] = ["# filo provenance report", ""]
    lines.append(f"Roots: {', '.join(chain.roots)}")
    lines.append(f"Generated by {chain.generator}.")
    lines.append("")
    lines.append("| Artifact | Access | Declared licence | Evidence |")
    lines.append("|---|---|---|---|")
    for a in chain.artifacts.values():
        ev = a.licenses[0].evidence.url if a.licenses else ""
        lines.append(f"| `{a.id}` | {a.access.value} | {_license_cell(a)} | {ev} |")
    lines.append("")
    lines.append("## Gaps")
    lines.append(f"- artifacts: {len(chain.artifacts)}")
    lines.append(f"- no declared licence: {_count(chain, lambda a: _has(a, LicenseConfidence.ABSENT))}")
    lines.append(f"- opaque licence: {_count(chain, lambda a: _has(a, LicenseConfidence.OPAQUE))}")
    lines.append(
        f"- inaccessible (gated/not-found/error): "
        f"{_count(chain, lambda a: a.access is not AccessStatus.PUBLIC)}"
    )
    lines.append(f"- traversal truncated: {'yes' if chain.traversal.truncated else 'no'}")
    for reason in chain.traversal.truncation_reasons:
        lines.append(f"  - {reason}")
    lines.append("")
    lines.append(BOUNDARY_SENTENCE)
    return assert_factual("\n".join(lines))
